name: VPC deployment in AWS 
on:
  push:
    branches:
      main
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: clone our repository
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::129664017770:role/github_actions-oidc
          aws-region: eu-west-1
          role-session-name: GithubVPCDeploy
      
      - name: Terraform Set up
        uses: hasicorp/setup-terraform@v1
      
      - name: Terraform Initialization
        run: terraform init
      
      - name: Terraform Planning
        run: terraform plan

      - name: Terraform applying
        run: terraform apply -auto-approve

